name: "Draft release"

on:
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    name: "Create draft release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
          cache: 'npm'

      - name: Install latest npm
        run: npm install -g npm

      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
