name: "release"

on:
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  release:
    name: "Create new minor release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Setup git user
        run: |
            git config --global user.name github-actions[bot]
            git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
          cache: 'npm'

      - name: Install latest npm
        run: npm install -g npm

      - name: Install release-it
        run: npm install -g release-it

      - name: Create minor release
        run: release-it minor --ci --'git.commitMessage="v${version}"' --'git.tagName="v${version}"' --git.tagMatch='v[0-9][0-9].[0-1][0-9].[0-9]*' --git.requireCommits=true --github.release --'github.releaseName="v${version}"' --github.autoGenerate --no-npm
