name: "Create release"

on:
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  release:
    name: "Create new minor release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_REPO_ACCESS_TOKEN }}
      
      - name: Setup git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
          cache: 'npm'

      - name: Install latest npm
        run: npm install -g npm

      - name: Install release-it
        run: npm install -g release-it

      - name: Create minor release
        run: release-it minor --ci --'git.commitMessage="v${version}"' --'git.tagName="v${version}"' --git.requireCommits --github.release --'github.releaseName="v${version}"' --github.autoGenerate --no-npm.publish
